name: publish to nuget
on:
  workflow_dispatch:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      # Run GitVersion
      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          additionalArguments: '/updateprojectfiles'

      - name: Build
        run: dotnet build --configuration Release BiglerNet.Markdown/BiglerNet.Markdown.csproj

      - name: Pack NuGet
        run: dotnet pack  --configuration Release BiglerNet.Markdown/BiglerNet.Markdown.csproj -o:package --source https://api.nuget.org --no-symbols

      - name: Push package
        run: dotnet nuget push ./package/*.nupkg --api-key ${{secrets.NUGET_KEY}}
        